#define ESTIMATING_VALUE									(100)

/*
	MAXIMUM CHARACTER LENGTHS
	! + 1 for string terminator
*/

#define MAX_LENGTH_OF_QUERY											2000
#define MAX_LENGTH_OF_TRIGGER_NAME									1000
#define MAX_LENGTH_OF_VAR											20
#define MAX_LENGTH_OF_DBNAME										ESTIMATING_VALUE
#define MAX_LENGTH_OF_HOST											ESTIMATING_VALUE
#define MAX_LENGTH_OF_USERNAME										ESTIMATING_VALUE
#define MAX_LENGTH_OF_PASSWORD										ESTIMATING_VALUE
#define MAX_LENGTH_OF_OUTPUT_PATH									ESTIMATING_VALUE
#define MAX_LENGTH_OF_MV_NAME										ESTIMATING_VALUE
#define MAX_LENGTH_OF_FILE_NAME										ESTIMATING_VALUE
#define MAX_LENGTH_OF_PORT											5

/*
	MAXIMUM NUMBER OF ELEMENTS
*/

#define MAX_NUMBER_OF_ELEMENTS										50
#define MAX_NUMBER_OF_TABLES										10
#define MAX_NUMBER_OF_COLS											ESTIMATING_VALUE
#define MAX_NUMBER_OF_EXPRESSIONS									(MAX_NUMBER_OF_TABLES * 10)
#define MAX_NUMBER_OF_SELECT_ELEMENT								ESTIMATING_VALUE
